version: "3.7"

services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: client/flask/Dockerfile
      args:
        - ENVIRONMENT=development
        - PORT=5000
    volumes:
      - .:/app
      - flask-static:/app/static
    ports:
      - 5000:5000

volumes:
    flask-static:
